/* automatically updated enum variants to CamelCase */
/* automatically generated by rust-bindgen 0.72.1 */

#[allow(dead_code)]
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum MonitorCallType {
    InitMonitor = 0,
    AttestMonitor = 1,
    Attest = 2,
    LoadPolicy = 3,
    CreateZygote = 4,
    DeleteZygote = 5,
    CreateTrustlet = 6,
    DeleteTrustlet = 7,
    InvokeTrustlet = 8,
    WaitForTrustletResult = 9,
    CreateChannel = 10,
    DeleteChannel = 11,
    GetPublicKey = 12,
    SendPolicy = 13,
    ExecuteElf = 14,
    InferCall = 15,
    InferCallRet = 16,
    GetStat = 17,
    ResetStat = 18,
    TestCall = 19,
    ArgTest = 20,
    PromptGet = 21,
    ResponseStore = 22,
    GpuApi = 23,
    ModelStoreDelete = 24,
    ModelStoreLoadInit = 25,
    ModelStoreLoadData = 26,
    ModelStoreGet = 27,
    ModelStoreGetUndo = 28,
    LoraStoreDelete = 29,
    LoraStoreLoadInit = 30,
    LoraStoreLoadData = 31,
    LoraStoreGet = 32,
    LoraStoreGetUndo = 33,
    EngineStoreDelete = 34,
    EngineStoreLoadInit = 35,
    EngineStoreLoadData = 36,
    EngineStoreGet = 37,
    EngineStoreGetUndo = 38,
}
pub const MONITOR_CALL_TYPE_MAX_VALUE: u32 = 38;
