/* automatically generated by rust-bindgen 0.72.0 */

#[allow(dead_code)]
#[allow(non_upper_case_globals)]
impl CudaApiCall {
    pub const CUDA_API_CALL_cudaDeviceReset: CudaApiCall = CudaApiCall(0);
    pub const CUDA_API_CALL_cudaDeviceSynchronize: CudaApiCall = CudaApiCall(1);
    pub const CUDA_API_CALL_cudaDeviceSetLimit: CudaApiCall = CudaApiCall(2);
    pub const CUDA_API_CALL_cudaDeviceGetLimit: CudaApiCall = CudaApiCall(3);
    pub const CUDA_API_CALL_cudaDeviceGetTexture1DLinearMaxWidth: CudaApiCall = CudaApiCall(4);
    pub const CUDA_API_CALL_cudaDeviceGetCacheConfig: CudaApiCall = CudaApiCall(5);
    pub const CUDA_API_CALL_cudaDeviceGetStreamPriorityRange: CudaApiCall = CudaApiCall(6);
    pub const CUDA_API_CALL_cudaDeviceSetCacheConfig: CudaApiCall = CudaApiCall(7);
    pub const CUDA_API_CALL_cudaDeviceGetByPCIBusId: CudaApiCall = CudaApiCall(8);
    pub const CUDA_API_CALL_cudaDeviceGetPCIBusId: CudaApiCall = CudaApiCall(9);
    pub const CUDA_API_CALL_cudaIpcGetEventHandle: CudaApiCall = CudaApiCall(10);
    pub const CUDA_API_CALL_cudaIpcOpenEventHandle: CudaApiCall = CudaApiCall(11);
    pub const CUDA_API_CALL_cudaIpcGetMemHandle: CudaApiCall = CudaApiCall(12);
    pub const CUDA_API_CALL_cudaIpcOpenMemHandle: CudaApiCall = CudaApiCall(13);
    pub const CUDA_API_CALL_cudaIpcCloseMemHandle: CudaApiCall = CudaApiCall(14);
    pub const CUDA_API_CALL_cudaDeviceFlushGPUDirectRDMAWrites: CudaApiCall = CudaApiCall(15);
    pub const CUDA_API_CALL_cudaDeviceRegisterAsyncNotification: CudaApiCall = CudaApiCall(16);
    pub const CUDA_API_CALL_cudaDeviceUnregisterAsyncNotification: CudaApiCall =
        CudaApiCall(17);
    pub const CUDA_API_CALL_cudaGetLastError: CudaApiCall = CudaApiCall(18);
    pub const CUDA_API_CALL_cudaPeekAtLastError: CudaApiCall = CudaApiCall(19);
    pub const CUDA_API_CALL_cudaGetErrorName: CudaApiCall = CudaApiCall(20);
    pub const CUDA_API_CALL_cudaGetErrorString: CudaApiCall = CudaApiCall(21);
    pub const CUDA_API_CALL_cudaGetDeviceCount: CudaApiCall = CudaApiCall(22);
    pub const CUDA_API_CALL_cudaGetDeviceProperties_v2: CudaApiCall = CudaApiCall(23);
    pub const CUDA_API_CALL_cudaDeviceGetAttribute: CudaApiCall = CudaApiCall(24);
    pub const CUDA_API_CALL_cudaDeviceGetDefaultMemPool: CudaApiCall = CudaApiCall(25);
    pub const CUDA_API_CALL_cudaDeviceSetMemPool: CudaApiCall = CudaApiCall(26);
    pub const CUDA_API_CALL_cudaDeviceGetMemPool: CudaApiCall = CudaApiCall(27);
    pub const CUDA_API_CALL_cudaDeviceGetNvSciSyncAttributes: CudaApiCall = CudaApiCall(28);
    pub const CUDA_API_CALL_cudaDeviceGetP2PAttribute: CudaApiCall = CudaApiCall(29);
    pub const CUDA_API_CALL_cudaChooseDevice: CudaApiCall = CudaApiCall(30);
    pub const CUDA_API_CALL_cudaInitDevice: CudaApiCall = CudaApiCall(31);
    pub const CUDA_API_CALL_cudaSetDevice: CudaApiCall = CudaApiCall(32);
    pub const CUDA_API_CALL_cudaGetDevice: CudaApiCall = CudaApiCall(33);
    pub const CUDA_API_CALL_cudaSetValidDevices: CudaApiCall = CudaApiCall(34);
    pub const CUDA_API_CALL_cudaSetDeviceFlags: CudaApiCall = CudaApiCall(35);
    pub const CUDA_API_CALL_cudaGetDeviceFlags: CudaApiCall = CudaApiCall(36);
    pub const CUDA_API_CALL_cudaStreamCreate: CudaApiCall = CudaApiCall(37);
    pub const CUDA_API_CALL_cudaStreamCreateWithFlags: CudaApiCall = CudaApiCall(38);
    pub const CUDA_API_CALL_cudaStreamCreateWithPriority: CudaApiCall = CudaApiCall(39);
    pub const CUDA_API_CALL_cudaStreamGetPriority: CudaApiCall = CudaApiCall(40);
    pub const CUDA_API_CALL_cudaStreamGetFlags: CudaApiCall = CudaApiCall(41);
    pub const CUDA_API_CALL_cudaStreamGetId: CudaApiCall = CudaApiCall(42);
    pub const CUDA_API_CALL_cudaCtxResetPersistingL2Cache: CudaApiCall = CudaApiCall(43);
    pub const CUDA_API_CALL_cudaStreamCopyAttributes: CudaApiCall = CudaApiCall(44);
    pub const CUDA_API_CALL_cudaStreamGetAttribute: CudaApiCall = CudaApiCall(45);
    pub const CUDA_API_CALL_cudaStreamSetAttribute: CudaApiCall = CudaApiCall(46);
    pub const CUDA_API_CALL_cudaStreamDestroy: CudaApiCall = CudaApiCall(47);
    pub const CUDA_API_CALL_cudaStreamWaitEvent: CudaApiCall = CudaApiCall(48);
    pub const CUDA_API_CALL_cudaStreamAddCallback: CudaApiCall = CudaApiCall(49);
    pub const CUDA_API_CALL_cudaStreamSynchronize: CudaApiCall = CudaApiCall(50);
    pub const CUDA_API_CALL_cudaStreamQuery: CudaApiCall = CudaApiCall(51);
    pub const CUDA_API_CALL_cudaStreamAttachMemAsync: CudaApiCall = CudaApiCall(52);
    pub const CUDA_API_CALL_cudaStreamBeginCapture: CudaApiCall = CudaApiCall(53);
    pub const CUDA_API_CALL_cudaStreamBeginCaptureToGraph: CudaApiCall = CudaApiCall(54);
    pub const CUDA_API_CALL_cudaThreadExchangeStreamCaptureMode: CudaApiCall = CudaApiCall(55);
    pub const CUDA_API_CALL_cudaStreamEndCapture: CudaApiCall = CudaApiCall(56);
    pub const CUDA_API_CALL_cudaStreamIsCapturing: CudaApiCall = CudaApiCall(57);
    pub const CUDA_API_CALL_cudaStreamGetCaptureInfo_v2: CudaApiCall = CudaApiCall(58);
    pub const CUDA_API_CALL_cudaStreamGetCaptureInfo_v3: CudaApiCall = CudaApiCall(59);
    pub const CUDA_API_CALL_cudaStreamUpdateCaptureDependencies: CudaApiCall = CudaApiCall(60);
    pub const CUDA_API_CALL_cudaStreamUpdateCaptureDependencies_v2: CudaApiCall =
        CudaApiCall(61);
    pub const CUDA_API_CALL_cudaEventCreate: CudaApiCall = CudaApiCall(62);
    pub const CUDA_API_CALL_cudaEventCreateWithFlags: CudaApiCall = CudaApiCall(63);
    pub const CUDA_API_CALL_cudaEventRecord: CudaApiCall = CudaApiCall(64);
    pub const CUDA_API_CALL_cudaEventRecordWithFlags: CudaApiCall = CudaApiCall(65);
    pub const CUDA_API_CALL_cudaEventQuery: CudaApiCall = CudaApiCall(66);
    pub const CUDA_API_CALL_cudaEventSynchronize: CudaApiCall = CudaApiCall(67);
    pub const CUDA_API_CALL_cudaEventDestroy: CudaApiCall = CudaApiCall(68);
    pub const CUDA_API_CALL_cudaEventElapsedTime: CudaApiCall = CudaApiCall(69);
    pub const CUDA_API_CALL_cudaImportExternalMemory: CudaApiCall = CudaApiCall(70);
    pub const CUDA_API_CALL_cudaExternalMemoryGetMappedBuffer: CudaApiCall = CudaApiCall(71);
    pub const CUDA_API_CALL_cudaExternalMemoryGetMappedMipmappedArray: CudaApiCall =
        CudaApiCall(72);
    pub const CUDA_API_CALL_cudaDestroyExternalMemory: CudaApiCall = CudaApiCall(73);
    pub const CUDA_API_CALL_cudaImportExternalSemaphore: CudaApiCall = CudaApiCall(74);
    pub const CUDA_API_CALL_cudaSignalExternalSemaphoresAsync_v2: CudaApiCall = CudaApiCall(75);
    pub const CUDA_API_CALL_cudaWaitExternalSemaphoresAsync_v2: CudaApiCall = CudaApiCall(76);
    pub const CUDA_API_CALL_cudaDestroyExternalSemaphore: CudaApiCall = CudaApiCall(77);
    pub const CUDA_API_CALL_cudaLaunchKernel: CudaApiCall = CudaApiCall(78);
    pub const CUDA_API_CALL_cudaLaunchKernelExC: CudaApiCall = CudaApiCall(79);
    pub const CUDA_API_CALL_cudaLaunchCooperativeKernel: CudaApiCall = CudaApiCall(80);
    pub const CUDA_API_CALL_cudaFuncSetCacheConfig: CudaApiCall = CudaApiCall(81);
    pub const CUDA_API_CALL_cudaFuncGetAttributes: CudaApiCall = CudaApiCall(82);
    pub const CUDA_API_CALL_cudaFuncSetAttribute: CudaApiCall = CudaApiCall(83);
    pub const CUDA_API_CALL_cudaFuncGetName: CudaApiCall = CudaApiCall(84);
    pub const CUDA_API_CALL_cudaFuncGetParamInfo: CudaApiCall = CudaApiCall(85);
    pub const CUDA_API_CALL_cudaLaunchHostFunc: CudaApiCall = CudaApiCall(86);
    pub const CUDA_API_CALL_cudaOccupancyMaxActiveBlocksPerMultiprocessor: CudaApiCall =
        CudaApiCall(87);
    pub const CUDA_API_CALL_cudaOccupancyAvailableDynamicSMemPerBlock: CudaApiCall =
        CudaApiCall(88);
    pub const CUDA_API_CALL_cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags: CudaApiCall =
        CudaApiCall(89);
    pub const CUDA_API_CALL_cudaOccupancyMaxPotentialClusterSize: CudaApiCall = CudaApiCall(90);
    pub const CUDA_API_CALL_cudaOccupancyMaxActiveClusters: CudaApiCall = CudaApiCall(91);
    pub const CUDA_API_CALL_cudaMallocManaged: CudaApiCall = CudaApiCall(92);
    pub const CUDA_API_CALL_cudaMalloc: CudaApiCall = CudaApiCall(93);
    pub const CUDA_API_CALL_cudaMallocHost: CudaApiCall = CudaApiCall(94);
    pub const CUDA_API_CALL_cudaMallocPitch: CudaApiCall = CudaApiCall(95);
    pub const CUDA_API_CALL_cudaMallocArray: CudaApiCall = CudaApiCall(96);
    pub const CUDA_API_CALL_cudaFree: CudaApiCall = CudaApiCall(97);
    pub const CUDA_API_CALL_cudaFreeHost: CudaApiCall = CudaApiCall(98);
    pub const CUDA_API_CALL_cudaFreeArray: CudaApiCall = CudaApiCall(99);
    pub const CUDA_API_CALL_cudaFreeMipmappedArray: CudaApiCall = CudaApiCall(100);
    pub const CUDA_API_CALL_cudaHostAlloc: CudaApiCall = CudaApiCall(101);
    pub const CUDA_API_CALL_cudaHostRegister: CudaApiCall = CudaApiCall(102);
    pub const CUDA_API_CALL_cudaHostUnregister: CudaApiCall = CudaApiCall(103);
    pub const CUDA_API_CALL_cudaHostGetDevicePointer: CudaApiCall = CudaApiCall(104);
    pub const CUDA_API_CALL_cudaHostGetFlags: CudaApiCall = CudaApiCall(105);
    pub const CUDA_API_CALL_cudaMalloc3D: CudaApiCall = CudaApiCall(106);
    pub const CUDA_API_CALL_cudaMalloc3DArray: CudaApiCall = CudaApiCall(107);
    pub const CUDA_API_CALL_cudaMallocMipmappedArray: CudaApiCall = CudaApiCall(108);
    pub const CUDA_API_CALL_cudaGetMipmappedArrayLevel: CudaApiCall = CudaApiCall(109);
    pub const CUDA_API_CALL_cudaMemcpy3D: CudaApiCall = CudaApiCall(110);
    pub const CUDA_API_CALL_cudaMemcpy3DPeer: CudaApiCall = CudaApiCall(111);
    pub const CUDA_API_CALL_cudaMemcpy3DAsync: CudaApiCall = CudaApiCall(112);
    pub const CUDA_API_CALL_cudaMemcpy3DPeerAsync: CudaApiCall = CudaApiCall(113);
    pub const CUDA_API_CALL_cudaMemGetInfo: CudaApiCall = CudaApiCall(114);
    pub const CUDA_API_CALL_cudaArrayGetInfo: CudaApiCall = CudaApiCall(115);
    pub const CUDA_API_CALL_cudaArrayGetPlane: CudaApiCall = CudaApiCall(116);
    pub const CUDA_API_CALL_cudaArrayGetMemoryRequirements: CudaApiCall = CudaApiCall(117);
    pub const CUDA_API_CALL_cudaMipmappedArrayGetMemoryRequirements: CudaApiCall =
        CudaApiCall(118);
    pub const CUDA_API_CALL_cudaArrayGetSparseProperties: CudaApiCall = CudaApiCall(119);
    pub const CUDA_API_CALL_cudaMipmappedArrayGetSparseProperties: CudaApiCall =
        CudaApiCall(120);
    pub const CUDA_API_CALL_cudaMemcpy: CudaApiCall = CudaApiCall(121);
    pub const CUDA_API_CALL_cudaMemcpyPeer: CudaApiCall = CudaApiCall(122);
    pub const CUDA_API_CALL_cudaMemcpy2D: CudaApiCall = CudaApiCall(123);
    pub const CUDA_API_CALL_cudaMemcpy2DToArray: CudaApiCall = CudaApiCall(124);
    pub const CUDA_API_CALL_cudaMemcpy2DFromArray: CudaApiCall = CudaApiCall(125);
    pub const CUDA_API_CALL_cudaMemcpy2DArrayToArray: CudaApiCall = CudaApiCall(126);
    pub const CUDA_API_CALL_cudaMemcpyToSymbol: CudaApiCall = CudaApiCall(127);
    pub const CUDA_API_CALL_cudaMemcpyFromSymbol: CudaApiCall = CudaApiCall(128);
    pub const CUDA_API_CALL_cudaMemcpyAsync: CudaApiCall = CudaApiCall(129);
    pub const CUDA_API_CALL_cudaMemcpyPeerAsync: CudaApiCall = CudaApiCall(130);
    pub const CUDA_API_CALL_cudaMemcpy2DAsync: CudaApiCall = CudaApiCall(131);
    pub const CUDA_API_CALL_cudaMemcpy2DToArrayAsync: CudaApiCall = CudaApiCall(132);
    pub const CUDA_API_CALL_cudaMemcpy2DFromArrayAsync: CudaApiCall = CudaApiCall(133);
    pub const CUDA_API_CALL_cudaMemcpyToSymbolAsync: CudaApiCall = CudaApiCall(134);
    pub const CUDA_API_CALL_cudaMemcpyFromSymbolAsync: CudaApiCall = CudaApiCall(135);
    pub const CUDA_API_CALL_cudaMemset: CudaApiCall = CudaApiCall(136);
    pub const CUDA_API_CALL_cudaMemset2D: CudaApiCall = CudaApiCall(137);
    pub const CUDA_API_CALL_cudaMemset3D: CudaApiCall = CudaApiCall(138);
    pub const CUDA_API_CALL_cudaMemsetAsync: CudaApiCall = CudaApiCall(139);
    pub const CUDA_API_CALL_cudaMemset2DAsync: CudaApiCall = CudaApiCall(140);
    pub const CUDA_API_CALL_cudaMemset3DAsync: CudaApiCall = CudaApiCall(141);
    pub const CUDA_API_CALL_cudaGetSymbolAddress: CudaApiCall = CudaApiCall(142);
    pub const CUDA_API_CALL_cudaGetSymbolSize: CudaApiCall = CudaApiCall(143);
    pub const CUDA_API_CALL_cudaMemPrefetchAsync: CudaApiCall = CudaApiCall(144);
    pub const CUDA_API_CALL_cudaMemPrefetchAsync_v2: CudaApiCall = CudaApiCall(145);
    pub const CUDA_API_CALL_cudaMemAdvise: CudaApiCall = CudaApiCall(146);
    pub const CUDA_API_CALL_cudaMemAdvise_v2: CudaApiCall = CudaApiCall(147);
    pub const CUDA_API_CALL_cudaMemRangeGetAttribute: CudaApiCall = CudaApiCall(148);
    pub const CUDA_API_CALL_cudaMemRangeGetAttributes: CudaApiCall = CudaApiCall(149);
    pub const CUDA_API_CALL_cudaMallocAsync: CudaApiCall = CudaApiCall(150);
    pub const CUDA_API_CALL_cudaFreeAsync: CudaApiCall = CudaApiCall(151);
    pub const CUDA_API_CALL_cudaMemPoolTrimTo: CudaApiCall = CudaApiCall(152);
    pub const CUDA_API_CALL_cudaMemPoolSetAttribute: CudaApiCall = CudaApiCall(153);
    pub const CUDA_API_CALL_cudaMemPoolGetAttribute: CudaApiCall = CudaApiCall(154);
    pub const CUDA_API_CALL_cudaMemPoolSetAccess: CudaApiCall = CudaApiCall(155);
    pub const CUDA_API_CALL_cudaMemPoolGetAccess: CudaApiCall = CudaApiCall(156);
    pub const CUDA_API_CALL_cudaMemPoolCreate: CudaApiCall = CudaApiCall(157);
    pub const CUDA_API_CALL_cudaMemPoolDestroy: CudaApiCall = CudaApiCall(158);
    pub const CUDA_API_CALL_cudaMallocFromPoolAsync: CudaApiCall = CudaApiCall(159);
    pub const CUDA_API_CALL_cudaMemPoolExportToShareableHandle: CudaApiCall = CudaApiCall(160);
    pub const CUDA_API_CALL_cudaMemPoolImportFromShareableHandle: CudaApiCall =
        CudaApiCall(161);
    pub const CUDA_API_CALL_cudaMemPoolExportPointer: CudaApiCall = CudaApiCall(162);
    pub const CUDA_API_CALL_cudaMemPoolImportPointer: CudaApiCall = CudaApiCall(163);
    pub const CUDA_API_CALL_cudaPointerGetAttributes: CudaApiCall = CudaApiCall(164);
    pub const CUDA_API_CALL_cudaDeviceCanAccessPeer: CudaApiCall = CudaApiCall(165);
    pub const CUDA_API_CALL_cudaDeviceEnablePeerAccess: CudaApiCall = CudaApiCall(166);
    pub const CUDA_API_CALL_cudaDeviceDisablePeerAccess: CudaApiCall = CudaApiCall(167);
    pub const CUDA_API_CALL_cudaGraphicsUnregisterResource: CudaApiCall = CudaApiCall(168);
    pub const CUDA_API_CALL_cudaGraphicsResourceSetMapFlags: CudaApiCall = CudaApiCall(169);
    pub const CUDA_API_CALL_cudaGraphicsMapResources: CudaApiCall = CudaApiCall(170);
    pub const CUDA_API_CALL_cudaGraphicsUnmapResources: CudaApiCall = CudaApiCall(171);
    pub const CUDA_API_CALL_cudaGraphicsResourceGetMappedPointer: CudaApiCall =
        CudaApiCall(172);
    pub const CUDA_API_CALL_cudaGraphicsSubResourceGetMappedArray: CudaApiCall =
        CudaApiCall(173);
    pub const CUDA_API_CALL_cudaGraphicsResourceGetMappedMipmappedArray: CudaApiCall =
        CudaApiCall(174);
    pub const CUDA_API_CALL_cudaGetChannelDesc: CudaApiCall = CudaApiCall(175);
    pub const CUDA_API_CALL_cudaCreateChannelDesc: CudaApiCall = CudaApiCall(176);
    pub const CUDA_API_CALL_cudaCreateTextureObject: CudaApiCall = CudaApiCall(177);
    pub const CUDA_API_CALL_cudaDestroyTextureObject: CudaApiCall = CudaApiCall(178);
    pub const CUDA_API_CALL_cudaGetTextureObjectResourceDesc: CudaApiCall = CudaApiCall(179);
    pub const CUDA_API_CALL_cudaGetTextureObjectTextureDesc: CudaApiCall = CudaApiCall(180);
    pub const CUDA_API_CALL_cudaGetTextureObjectResourceViewDesc: CudaApiCall =
        CudaApiCall(181);
    pub const CUDA_API_CALL_cudaCreateSurfaceObject: CudaApiCall = CudaApiCall(182);
    pub const CUDA_API_CALL_cudaDestroySurfaceObject: CudaApiCall = CudaApiCall(183);
    pub const CUDA_API_CALL_cudaGetSurfaceObjectResourceDesc: CudaApiCall = CudaApiCall(184);
    pub const CUDA_API_CALL_cudaDriverGetVersion: CudaApiCall = CudaApiCall(185);
    pub const CUDA_API_CALL_cudaRuntimeGetVersion: CudaApiCall = CudaApiCall(186);
    pub const CUDA_API_CALL_cudaGraphCreate: CudaApiCall = CudaApiCall(187);
    pub const CUDA_API_CALL_cudaGraphAddKernelNode: CudaApiCall = CudaApiCall(188);
    pub const CUDA_API_CALL_cudaGraphKernelNodeGetParams: CudaApiCall = CudaApiCall(189);
    pub const CUDA_API_CALL_cudaGraphKernelNodeSetParams: CudaApiCall = CudaApiCall(190);
    pub const CUDA_API_CALL_cudaGraphKernelNodeCopyAttributes: CudaApiCall = CudaApiCall(191);
    pub const CUDA_API_CALL_cudaGraphKernelNodeGetAttribute: CudaApiCall = CudaApiCall(192);
    pub const CUDA_API_CALL_cudaGraphKernelNodeSetAttribute: CudaApiCall = CudaApiCall(193);
    pub const CUDA_API_CALL_cudaGraphAddMemcpyNode: CudaApiCall = CudaApiCall(194);
    pub const CUDA_API_CALL_cudaGraphAddMemcpyNodeToSymbol: CudaApiCall = CudaApiCall(195);
    pub const CUDA_API_CALL_cudaGraphAddMemcpyNodeFromSymbol: CudaApiCall = CudaApiCall(196);
    pub const CUDA_API_CALL_cudaGraphAddMemcpyNode1D: CudaApiCall = CudaApiCall(197);
    pub const CUDA_API_CALL_cudaGraphMemcpyNodeGetParams: CudaApiCall = CudaApiCall(198);
    pub const CUDA_API_CALL_cudaGraphMemcpyNodeSetParams: CudaApiCall = CudaApiCall(199);
    pub const CUDA_API_CALL_cudaGraphMemcpyNodeSetParamsToSymbol: CudaApiCall =
        CudaApiCall(200);
    pub const CUDA_API_CALL_cudaGraphMemcpyNodeSetParamsFromSymbol: CudaApiCall =
        CudaApiCall(201);
    pub const CUDA_API_CALL_cudaGraphMemcpyNodeSetParams1D: CudaApiCall = CudaApiCall(202);
    pub const CUDA_API_CALL_cudaGraphAddMemsetNode: CudaApiCall = CudaApiCall(203);
    pub const CUDA_API_CALL_cudaGraphMemsetNodeGetParams: CudaApiCall = CudaApiCall(204);
    pub const CUDA_API_CALL_cudaGraphMemsetNodeSetParams: CudaApiCall = CudaApiCall(205);
    pub const CUDA_API_CALL_cudaGraphAddHostNode: CudaApiCall = CudaApiCall(206);
    pub const CUDA_API_CALL_cudaGraphHostNodeGetParams: CudaApiCall = CudaApiCall(207);
    pub const CUDA_API_CALL_cudaGraphHostNodeSetParams: CudaApiCall = CudaApiCall(208);
    pub const CUDA_API_CALL_cudaGraphAddChildGraphNode: CudaApiCall = CudaApiCall(209);
    pub const CUDA_API_CALL_cudaGraphChildGraphNodeGetGraph: CudaApiCall = CudaApiCall(210);
    pub const CUDA_API_CALL_cudaGraphAddEmptyNode: CudaApiCall = CudaApiCall(211);
    pub const CUDA_API_CALL_cudaGraphAddEventRecordNode: CudaApiCall = CudaApiCall(212);
    pub const CUDA_API_CALL_cudaGraphEventRecordNodeGetEvent: CudaApiCall = CudaApiCall(213);
    pub const CUDA_API_CALL_cudaGraphEventRecordNodeSetEvent: CudaApiCall = CudaApiCall(214);
    pub const CUDA_API_CALL_cudaGraphAddEventWaitNode: CudaApiCall = CudaApiCall(215);
    pub const CUDA_API_CALL_cudaGraphEventWaitNodeGetEvent: CudaApiCall = CudaApiCall(216);
    pub const CUDA_API_CALL_cudaGraphEventWaitNodeSetEvent: CudaApiCall = CudaApiCall(217);
    pub const CUDA_API_CALL_cudaGraphAddExternalSemaphoresSignalNode: CudaApiCall =
        CudaApiCall(218);
    pub const CUDA_API_CALL_cudaGraphExternalSemaphoresSignalNodeGetParams: CudaApiCall =
        CudaApiCall(219);
    pub const CUDA_API_CALL_cudaGraphExternalSemaphoresSignalNodeSetParams: CudaApiCall =
        CudaApiCall(220);
    pub const CUDA_API_CALL_cudaGraphAddExternalSemaphoresWaitNode: CudaApiCall =
        CudaApiCall(221);
    pub const CUDA_API_CALL_cudaGraphExternalSemaphoresWaitNodeGetParams: CudaApiCall =
        CudaApiCall(222);
    pub const CUDA_API_CALL_cudaGraphExternalSemaphoresWaitNodeSetParams: CudaApiCall =
        CudaApiCall(223);
    pub const CUDA_API_CALL_cudaGraphAddMemAllocNode: CudaApiCall = CudaApiCall(224);
    pub const CUDA_API_CALL_cudaGraphMemAllocNodeGetParams: CudaApiCall = CudaApiCall(225);
    pub const CUDA_API_CALL_cudaGraphAddMemFreeNode: CudaApiCall = CudaApiCall(226);
    pub const CUDA_API_CALL_cudaGraphMemFreeNodeGetParams: CudaApiCall = CudaApiCall(227);
    pub const CUDA_API_CALL_cudaDeviceGraphMemTrim: CudaApiCall = CudaApiCall(228);
    pub const CUDA_API_CALL_cudaDeviceGetGraphMemAttribute: CudaApiCall = CudaApiCall(229);
    pub const CUDA_API_CALL_cudaDeviceSetGraphMemAttribute: CudaApiCall = CudaApiCall(230);
    pub const CUDA_API_CALL_cudaGraphClone: CudaApiCall = CudaApiCall(231);
    pub const CUDA_API_CALL_cudaGraphNodeFindInClone: CudaApiCall = CudaApiCall(232);
    pub const CUDA_API_CALL_cudaGraphNodeGetType: CudaApiCall = CudaApiCall(233);
    pub const CUDA_API_CALL_cudaGraphGetNodes: CudaApiCall = CudaApiCall(234);
    pub const CUDA_API_CALL_cudaGraphGetRootNodes: CudaApiCall = CudaApiCall(235);
    pub const CUDA_API_CALL_cudaGraphGetEdges: CudaApiCall = CudaApiCall(236);
    pub const CUDA_API_CALL_cudaGraphGetEdges_v2: CudaApiCall = CudaApiCall(237);
    pub const CUDA_API_CALL_cudaGraphNodeGetDependencies: CudaApiCall = CudaApiCall(238);
    pub const CUDA_API_CALL_cudaGraphNodeGetDependencies_v2: CudaApiCall = CudaApiCall(239);
    pub const CUDA_API_CALL_cudaGraphNodeGetDependentNodes: CudaApiCall = CudaApiCall(240);
    pub const CUDA_API_CALL_cudaGraphNodeGetDependentNodes_v2: CudaApiCall = CudaApiCall(241);
    pub const CUDA_API_CALL_cudaGraphAddDependencies: CudaApiCall = CudaApiCall(242);
    pub const CUDA_API_CALL_cudaGraphAddDependencies_v2: CudaApiCall = CudaApiCall(243);
    pub const CUDA_API_CALL_cudaGraphRemoveDependencies: CudaApiCall = CudaApiCall(244);
    pub const CUDA_API_CALL_cudaGraphRemoveDependencies_v2: CudaApiCall = CudaApiCall(245);
    pub const CUDA_API_CALL_cudaGraphDestroyNode: CudaApiCall = CudaApiCall(246);
    pub const CUDA_API_CALL_cudaGraphInstantiate: CudaApiCall = CudaApiCall(247);
    pub const CUDA_API_CALL_cudaGraphInstantiateWithFlags: CudaApiCall = CudaApiCall(248);
    pub const CUDA_API_CALL_cudaGraphInstantiateWithParams: CudaApiCall = CudaApiCall(249);
    pub const CUDA_API_CALL_cudaGraphExecGetFlags: CudaApiCall = CudaApiCall(250);
    pub const CUDA_API_CALL_cudaGraphExecKernelNodeSetParams: CudaApiCall = CudaApiCall(251);
    pub const CUDA_API_CALL_cudaGraphExecMemcpyNodeSetParams: CudaApiCall = CudaApiCall(252);
    pub const CUDA_API_CALL_cudaGraphExecMemcpyNodeSetParamsToSymbol: CudaApiCall =
        CudaApiCall(253);
    pub const CUDA_API_CALL_cudaGraphExecMemcpyNodeSetParamsFromSymbol: CudaApiCall =
        CudaApiCall(254);
    pub const CUDA_API_CALL_cudaGraphExecMemcpyNodeSetParams1D: CudaApiCall = CudaApiCall(255);
    pub const CUDA_API_CALL_cudaGraphExecMemsetNodeSetParams: CudaApiCall = CudaApiCall(256);
    pub const CUDA_API_CALL_cudaGraphExecHostNodeSetParams: CudaApiCall = CudaApiCall(257);
    pub const CUDA_API_CALL_cudaGraphExecChildGraphNodeSetParams: CudaApiCall =
        CudaApiCall(258);
    pub const CUDA_API_CALL_cudaGraphExecEventRecordNodeSetEvent: CudaApiCall =
        CudaApiCall(259);
    pub const CUDA_API_CALL_cudaGraphExecEventWaitNodeSetEvent: CudaApiCall = CudaApiCall(260);
    pub const CUDA_API_CALL_cudaGraphExecExternalSemaphoresSignalNodeSetParams: CudaApiCall =
        CudaApiCall(261);
    pub const CUDA_API_CALL_cudaGraphExecExternalSemaphoresWaitNodeSetParams: CudaApiCall =
        CudaApiCall(262);
    pub const CUDA_API_CALL_cudaGraphNodeSetEnabled: CudaApiCall = CudaApiCall(263);
    pub const CUDA_API_CALL_cudaGraphNodeGetEnabled: CudaApiCall = CudaApiCall(264);
    pub const CUDA_API_CALL_cudaGraphExecUpdate: CudaApiCall = CudaApiCall(265);
    pub const CUDA_API_CALL_cudaGraphUpload: CudaApiCall = CudaApiCall(266);
    pub const CUDA_API_CALL_cudaGraphLaunch: CudaApiCall = CudaApiCall(267);
    pub const CUDA_API_CALL_cudaGraphExecDestroy: CudaApiCall = CudaApiCall(268);
    pub const CUDA_API_CALL_cudaGraphDestroy: CudaApiCall = CudaApiCall(269);
    pub const CUDA_API_CALL_cudaGraphDebugDotPrint: CudaApiCall = CudaApiCall(270);
    pub const CUDA_API_CALL_cudaUserObjectCreate: CudaApiCall = CudaApiCall(271);
    pub const CUDA_API_CALL_cudaUserObjectRetain: CudaApiCall = CudaApiCall(272);
    pub const CUDA_API_CALL_cudaUserObjectRelease: CudaApiCall = CudaApiCall(273);
    pub const CUDA_API_CALL_cudaGraphRetainUserObject: CudaApiCall = CudaApiCall(274);
    pub const CUDA_API_CALL_cudaGraphReleaseUserObject: CudaApiCall = CudaApiCall(275);
    pub const CUDA_API_CALL_cudaGraphAddNode: CudaApiCall = CudaApiCall(276);
    pub const CUDA_API_CALL_cudaGraphAddNode_v2: CudaApiCall = CudaApiCall(277);
    pub const CUDA_API_CALL_cudaGraphNodeSetParams: CudaApiCall = CudaApiCall(278);
    pub const CUDA_API_CALL_cudaGraphExecNodeSetParams: CudaApiCall = CudaApiCall(279);
    pub const CUDA_API_CALL_cudaGraphConditionalHandleCreate: CudaApiCall = CudaApiCall(280);
    pub const CUDA_API_CALL_cudaGetDriverEntryPoint: CudaApiCall = CudaApiCall(281);
    pub const CUDA_API_CALL_cudaGetDriverEntryPointByVersion: CudaApiCall = CudaApiCall(282);
    pub const CUDA_API_CALL_cudaGetExportTable: CudaApiCall = CudaApiCall(283);
    pub const CUDA_API_CALL_cudaGetFuncBySymbol: CudaApiCall = CudaApiCall(284);
    pub const CUDA_API_CALL_cudaGetKernel: CudaApiCall = CudaApiCall(285);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CudaApiCall(pub u64);
