/* automatically updated type variants to CamelCase */
/* automatically generated by rust-bindgen 0.72.0 */

#[deny(warnings)]
#[allow(non_upper_case_globals)]
impl ProcessCallType {
    pub const Fail: ProcessCallType = ProcessCallType(1342177279);
    pub const Exit: ProcessCallType = ProcessCallType(1342177278);
    pub const DebugPrint: ProcessCallType = ProcessCallType(1342177277);
    pub const VirtAlloc: ProcessCallType = ProcessCallType(1342177276);
    pub const Map: ProcessCallType = ProcessCallType(1342177275);
    pub const SetTcb: ProcessCallType = ProcessCallType(1342177274);
    pub const Mprotect: ProcessCallType = ProcessCallType(1342177273);
    pub const GetResult: ProcessCallType = ProcessCallType(1342177272);
    pub const GuestRequest: ProcessCallType = ProcessCallType(1342177271);
    pub const VirtFree: ProcessCallType = ProcessCallType(1342177270);
    pub const Nop: ProcessCallType = ProcessCallType(1342177269);
    pub const Finalize: ProcessCallType = ProcessCallType(1342177268);
    pub const Inference: ProcessCallType = ProcessCallType(1342177267);
    pub const GpuChannel: ProcessCallType = ProcessCallType(1342177266);
    pub const Exception: ProcessCallType = ProcessCallType(1325400063);
    pub const HandleDf: ProcessCallType = ProcessCallType(1325400062);
    pub const CallOutb: ProcessCallType = ProcessCallType(1342177184);
    pub const CallExit: ProcessCallType = ProcessCallType(1342177185);
    pub const CallOutbWithValue: ProcessCallType = ProcessCallType(1342177186);
    pub const CallInflateChannel: ProcessCallType = ProcessCallType(1342177187);
    pub const TbrDebug: ProcessCallType = ProcessCallType(99);
    pub const TbrDebugPrint: ProcessCallType = ProcessCallType(100);
}
#[allow(dead_code)]
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ProcessCallType(pub u64);
